config/routes.rb
Rails.application.routes.draw do
 #top
root 'posts#index'

post'posts/create'=>'posts#create',as: 'posts'
#singup
#  resource :sessions, only: [:new, :create, :destroy]
get 'login' => 'sessions#new' 
post 'login'=>'sessions#create' ,as: 'sessions'
delete 'logout'=>'sessions#destroy'
#login
get 'signup' => 'users#new', as: 'signup'
post "users/create" => 'users#create', as: 'user'
#mypage
get 'mypage' =>'users#mypage', as: 'mypage'

get 'post' => 'posts#show'
get 'users' => 'users#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
     def user
         User.find(self.user_id)
         
     end
end

app/models/user.rb
class User < ApplicationRecord
    
     has_secure_password
     def posts
         #puts "hello iam"
         Post.where(user_id: self.id)
     end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    
   
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   def index
     @post = Post.new
     @user = User.find_by(id: @post.user_id)
     @posts = Post.all
   end
   

  def show
   
    @post = Post.find_by(id: params[:id])
   
  end
  
  def create
      @post = Post.new( post_params)
      #@post.user_id = current_user.id

       if @post.save
        session[:user]
    
          redirect_to'/'
    
       else
          render 'new'
       end
  end
   private
        def post_params
             params.require(:post).permit(:title, :content)
        end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        
    end
    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
         session[:user_id] = @user.id
          redirect_to '/'
        else
          p user.errors.full_messages
          flash.now[:danger] = 'Invalid email/password combination'
          render 'new'
        end
    end
    def destroy

    session[:user_id] = nil
    redirect_to root_path

    

    end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user= User.new
  end

  def create
   user=User.new(user_params)
    if user.save
      login(user)
      redirect_to root_path
    else
      render :new
    end  


  end
  def show 
   @user = User.find( parmas[:id])
  end
  
  def mypage
    @user = User.find(session[:user_id])
  end
  
  private
    def user_params
        params.require(:user).permit(:name, :email,:password,:password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
      def login(user)
           session[:user_id] = user.id
      end
      
       def current_user
            if session[:user_id]
              User.find(session[:user_id])
            #else
             #   redirect_to singup_path
            end
       end
       
           
        def logged_in?
          !current_user.nil?
        end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App0818</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
        <a href="/">Home</a>
        <%= link_to "ユーザー一覧","/users" %>
        <%= link_to "投稿一覧", root_path %>
        <a href="/mypage">マイページ</a>
        <%= link_to "ログアウト", "/logout", method: :delete %>
    <% else %>
        <a href="/">Home</a>
        <%= link_to '会員登録', signup_path %>
        <a href="/login">ログイン</a>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>
<% if session[:user_id] %>
    <%= form_for @post, url: posts_path do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :body %>
    <%= f.text_field :body %>
    <%= f.submit %>
    <% end %>
    
  <p><% @posts.each do |post|%>
       <%=link_to post.title,"/post" %>|<%= post.updated_at %>｜
       <%=User.find(session[:user_id]).name%>さんの投稿<br>
       <% end %></p>
   
<% else %>
<p> <%= link_to "ログイン","/login"%> </p>
<p> <% @posts.each do |post|%>
       <%=link_to post.title,"/post" %>|<%= post.updated_at %>｜
       <%= post.user_id%>さんの投稿<br>
       <% end %></p>
 
<% end %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>


   タイトル:<%= post.title %>|<%= post.updated_at %>｜<%=  投稿者：<%= current_user.name%>
   
  
  
  

app/views/users/mypage.html.erb
<br>
<br>

<h1><br><%= @user.name %>さんのマイページ<br></h1>
 
 
<h1>Users#mypage</h1>
<p>Find me in app/views/users/mypage.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>
<%= form_for @user, url: user_path do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name%>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation%>
    <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<br> 
<h1>ユーザー一覧</h1>